name: 'Catchy Code Complexity Analyzer'
description: 'Analyzes code complexity in Pull Requests for C/C++ and Python'
author: 'miguelcsx'

inputs:
  threshold:
    description: 'Minimum complexity threshold'
    required: false
    default: '10'

runs:
  using: "composite"
  steps:
    - name: Checkout Catchy
      uses: actions/checkout@v4
      with:
        repository: miguelcsx/catchy
        path: catchy

    - name: Setup Mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: catchy/catchy.yml
        environment-name: catchy
        
    - name: Build Catchy
      shell: bash -l {0}
      run: |
        cd catchy
        cmake -B build -S . -G Ninja
        cmake --build build
        
    - name: Get PR Files
      id: pr-files
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ''
        
    - name: Analyze Files
      shell: bash -l {0}
      run: |
        cd catchy
        HIGH_COMPLEXITY=false
        for file in ${{ steps.pr-files.outputs.files}}; do
          if [[ $file =~ \.(cpp|hpp|h|c|py)$ ]] && [ -f "../$file" ]; then
            echo "Analyzing $file..."
            if ! ./build/catchy "../$file" --threshold=${{ inputs.threshold }}; then
              HIGH_COMPLEXITY=true
            fi
          fi
        done
        
        if [ "$HIGH_COMPLEXITY" = true ]; then
          echo "❌ Some files exceed complexity threshold of ${{ inputs.threshold }}"
          exit 1
        else
          echo "✅ All files passed complexity check"
        fi

branding:
  icon: 'anchor'
  color: 'blue'
