name: Code Complexity Check
on:
  pull_request:
  push:
    branches: [ main ]  # or your default branch
jobs:
  complexity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Add this
      - uses: miguelcsx/catchy@v1.0.3
        with:
          threshold: '10'
